### ISSUE TITLE
Grant Admin Permissions to an External Group needs to clarify which steps are SAML vs LDAP only

### ISSUE THREAD

**Issue by matthewfischer** [cloudfoundry/docs-uaa#8]
In the Grant Admin Permissions to an External Group  section, steps 4 and 5 (see image) are ONLY for SAML, not LDAP and should be called out as such.  Step 3 is LDAP only. The current doc implies that you do 3-5 for both which is not correct.  Only Steps 1 & 2 are common.

<img width="710" alt="screen shot 2018-09-18 at 3 17 26 pm" src="https://user-images.githubusercontent.com/1686293/45717295-c450a080-bb56-11e8-9426-ea736250250d.png">

**Comment by pspinrad** [comment]
Thank you for this @matthewfischer -- super helpful, will fix.

**Comment by ljarzynski** [comment]
I've pushed a fix for this and it will appear on the site shortly.

**Comment by matthewfischer** [comment]
looks good thanks!
